### ISSUE TITLE
Live server is crashing with missing AbortController message

### ISSUE THREAD

**Issue by chr15m** [chr15m/twiiit.com#8]
```
2022-07-03 23:28:09 ReferenceError: AbortController is not defined
    at fetch_with_timeout (/home/piku/.piku/apps/twiiit/server.js:133:22)
    at /home/piku/.piku/apps/twiiit/server.js:154:7
    at new Promise (<anonymous>)
    at /home/piku/.piku/apps/twiiit/server.js:152:12
    at Array.map (<anonymous>)
    at test_server_list (/home/piku/.piku/apps/twiiit/server.js:151:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by chr15m** [comment]
Fixed in 6b266f7.
